### ISSUE TITLE
Character Encoding

### ISSUE THREAD

**Issue by Julius112** [bobboau/MPD.js#3] opened 2017-07-09 20:45 UTC
Hi bobboau,

I really like your js library. It works really good for me. The only problem I have is that some special chars (like Ü) aren't showing the right way (Ã instead). I've tried to change the pages encoding to iso-8859-1 (which is the encoding of the characters). However, it still showed the same way. Do you have an idea, what the solution is?

**Comment by chaseuyeda** [comment] 2017-07-23 17:08
I ran into this also, since I have lots of non-English music in my library. Suspicion of root cause is that MPD sends back all characters with UTF-8 encoding, but the encoding of the Bragi-MPD client (which I'm assuming you're using) is UTF-16.

You might be able to fix this just by changing the charset in index.html to be utf-8 instead of utf-16 (I actually haven't tried that even though it's the more obvious "first thing to try"), but I ended up just hacking every line in the Bragi-MPD client that could conceivably display a non-English character, for example:

```
function overrideMpd(){
//override the default MPD Song class to add some methods to it
var OrigonalSong = MPD.Song;
MPD.Song = function(client, source){
  var me = OrigonalSong(client, source);
  /**
    * get a DOM subtree for this song
    */
  me.getItemUI = function(template_id){
  if(typeof template_id === 'undefined'){
    template_id = 'template_LIST_song';
  }
 var contents = $($('#'+template_id).html());
 contents.find('.LIST_song_title').html(decodeURIComponent(escape(me.getDisplayName())));
 // hack to fix UTF-8-encoded data from MPD
 contents.find('.LIST_song_artist').html(decodeURIComponent(escape(me.getArtist())));
 contents.find('.LIST_song_album').html(decodeURIComponent(escape(me.getAlbum())));
 contents.find('.LIST_song_genre').html(decodeURIComponent(escape(me.getGenre())));
 contents.find('.LIST_song_path').html(decodeURIComponent(escape(me.getPath())));
 contents.find('.LIST_song_track').html(decodeURIComponent(escape(me.getTrack())));
 contents.find('.LIST_song_disk').html(me.getDisk());
 contents.find('.LIST_song_duration').html(formatTime(me.getDuration()));
 
return contents;
}
  return me;
}
```

This isn't a good solution in the long run because both of those functions are deprecated, IIRC, but it worked fine for me.

**Comment by Julius112** [comment] 2017-08-01 08:11
I actually already thought about something like that but setting encoding of my page to UTF-8 didn't solved the problem for me (which is really confusing I think).
Anyway, thanks for sharing your solution - I guess I will try the same on my project ;)

**Comment by bobboau** [comment] 2017-08-01 16:12
Just to let you guys know, I have not abandoned this project. I'll be looking into this issue soon. I'm in the middle of dealing with some hardware stuff right now (setting up a new installation in my car on a Raspberry Pi with a touch screen) and after that I'll be looking into this to see if there is a way MPD.js can better handle special characters as soon as I get my current hardware issues resolved. I am surprised I have not ran into this problem before, because I do have a few songs that I could have sworn had a few non-English text in some of their metadata. Or maybe I just dealt with it in my client code.

**Comment by C0DK** [comment] 2017-09-08 14:55
also ran into this issue - how is solving it going? would love to see some more concrete solution to the issue. 👍 Say the word if you need some help in anyway.

**Comment by bobboau** [comment] 2017-09-09 23:14
I'm actually having a hard time replicating this because I apparently don't have any music with Unicode in it's metadata and I don't have a tag editor installed. If you have a couple of test files that demonstrate this bug I can work on it.

**Comment by Julius112** [comment] 2017-09-10 09:54
I think you can download this one for free from Soundcloud:
https://soundcloud.com/flosstradamus/jack-u-x-post-malone-where-r-u-now-allen-iverson-flosstradamus-remix
That should include umlauts in the ID3 tags. If you have problems, please let me know.

**Comment by bobboau** [comment] 2017-09-10 16:50
I jumped through the hoops to get the free download and it seems to have no tags, or they are all set to "Unknown"

**Comment by bobboau** [comment] 2017-09-10 17:04
OK, I've managed to acquire a few on my own.

**Comment by bobboau** [comment] 2017-09-10 20:57
I have pushed a fix for this issue. I was only able to test with German and Japanese characters. I have concerns that there might still be problems with songs that have four byte characters, but I'll wait for someone to find a song with one of those to worry too much.

Things to pay particular attention to are files with multi-byte characters (just about anything outside the normal English alphanumeric set) in the file name, and that they function properly (can be played etc).

**Comment by Julius112** [comment] 2017-09-10 21:33
Great stuff - thanks a lot. The changes actually look way more complicated then I thought! I will definitely test this asap :)

**Comment by bobboau** [comment] 2017-09-10 23:26
yeah, I was expecting there to be some built in javascript function to fix it, but it looked like there was no support in the websockify library for converting from a utf-8 encoded byte sequence to a string, it just assumed every byte was a char code. which is not great, because javascript strings are UTF.

**Comment by bobboau** [comment] 2017-09-18 05:11
OK, I'm going to assume this fixed the problem.

**Closed as completed by bobboau** 2017-09-18 05:11 UTC

**Comment by Julius112** [comment] 2017-10-01 18:41
I finally found the time to test it! Problem solved :)
Thank you very much for your help!
